import 'dotenv/config';
import {
  createConversationManager,
  type ConversationManagerDependencies,
} from '../conversation/ConversationManager.js';
import type { ConversationState } from '../conversation/ConversationState.js';
import type { ConversationTurnResult } from '../conversation/actions.js';
import { createPromptBuilder } from '../conversation/PromptBuilder.js';
import { createDetectContradictionsService } from '../services/detectContradictions.js';
import { createDetectSeverityService } from '../services/detectSeverity.js';
import { createRecommendServicesService } from '../services/recommendServices.js';
import { createVerifyPolicyService } from '../services/verifyPolicy.js';

const dependencies: ConversationManagerDependencies = {
  verifyPolicy: createVerifyPolicyService(),
  detectSeverity: createDetectSeverityService(),
  detectContradictions: createDetectContradictionsService(),
  extractClaimData: {
    extract() {
      return Promise.resolve({
        acknowledgement: '',
        updatedClaim: {},
        missingFields: [],
        conversationStage: 'collecting_fnol',
        nextQuestion: '',
        conversationAnalysis: 'mock'
      });
    },
  },
  recommendServices: createRecommendServicesService(),
  generateSummary: {
    generate() {
      return {
        summary: 'Summary generation is outside Sprint 3.',
        severity: 'low',
      };
    },
  },
  claimLogger: {
    log() {
      return undefined;
    },
  },
  promptBuilder: createPromptBuilder(),
  geminiClient: {
    generateAssistantResponse() {
      return Promise.resolve({
        assistantResponse: 'Demo language response generated by the mock client.',
      });
    },
  },
  claimNumberGenerator: {
    generate() {
      return 'CLM-DEMO-0001';
    },
  },
};

function printState(label: string, state: ConversationState): void {
  console.log(`\n${label}`);
  console.log(`  step: ${state.currentConversationStep}`);
  console.log(`  collectedFields: ${state.collectedFields.join(', ') || 'none'}`);
  console.log(`  missingFields: ${state.missingFields.join(', ') || 'none'}`);
  console.log(`  retryCount: ${state.retryCount}`);
  console.log(`  severity: ${state.severity ?? 'not set'}`);
  console.log(`  escalationRequired: ${state.escalationRequired}`);
}

function printTurn(result: ConversationTurnResult): void {
  console.log(`  action: ${result.action.type}`);
  console.log(`  assistant: ${result.action.message}`);

  if (result.action.type === 'recommend_services') {
    console.log(`  services: ${result.action.services.join(', ') || 'none'}`);
  }

  if (result.action.type === 'complete') {
    console.log(`  claimReferenceNumber: ${result.action.claim.claimReferenceNumber}`);
  }
}

const manager = createConversationManager(dependencies);
let state = manager.start();

printState('Start conversation', state);
console.log(`  assistant: ${state.lastAssistantMessage ?? ''}`);

const messages = [
  'policyNumber=MMI-10234; callerName=Arjun Rao',
  [
    'dateOfIncident=2026-07-29',
    'timeOfIncident=09:30',
    'locationOfIncident=MG Road, Bengaluru',
    'incidentDescription=Two cars collided at a junction',
    'injuriesReported=false',
    'policeReportFiled=true',
    'policeReportReference=POL-123',
    'photosAvailable=true',
    'vehicleDrivable=false',
    'otherParties=One other driver involved',
  ].join('; '),
  'confirm=true',
];

for (const [index, message] of messages.entries()) {
  console.log(`\nUser ${index + 1}: ${message}`);
  const result = await manager.handleUserMessage(state, message);
  state = result.state;
  printTurn(result);
  printState(`After user ${index + 1}`, state);
}
